### ISSUE TITLE
nexus-repository-composer 0.0.2 does not work with Nexus OSS >3.19.0-01

### ISSUE THREAD

**Issue by func0der** [sonatype-nexus-community/nexus-repository-composer#49]
* **What are you trying to do?**
I am trying to use the current 0.0.2 with Nexus OSS >3.19.0-01. 

* **What feature or behavior is this required for?**
Using your plugin with an up-to-date version of Nexus OSS.

* **How could we solve this issue? (Not knowing is okay!)**
I think, that the dependency for `jline` got unpublished somehow. I could not find the place in the diff between 3.18.01-01 and 3.19.0-01 though.

* **Anything else?**
The error message during the docker build is the following:

```
Downloaded from rso-public-grid: https://repository.sonatype.org/content/groups/sonatype-public-grid/org/codehaus/groovy/groovy-eclipse-batch/2.4.3-01/groovy-eclipse-batch-2.4.3-01.jar (15 MB at 7.4 MB/s)
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java:[35,15] 1. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java (at line 35)
	import static jline.internal.Preconditions.checkNotNull;
	              ^^^^^
The import jline cannot be resolved

[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java:[56,21] 2. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java (at line 56)
	this.eventManager = checkNotNull(eventManager);
	                    ^^^^^^^^^^^^
The method checkNotNull(EventManager) is undefined for the type ComposerHostedMetadataFacetImpl

[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java:[32,15] 3. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java (at line 32)
	import static jline.internal.Preconditions.checkNotNull;
	              ^^^^^
The import jline cannot be resolved

[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java:[111,30] 4. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java (at line 111)
	this.composerJsonExtractor = checkNotNull(composerJsonExtractor);
	                             ^^^^^^^^^^^^
The method checkNotNull(ComposerJsonExtractor) is undefined for the type ComposerFormatAttributesExtractor

[ERROR] Found 4 errors and 0 warnings.
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:45 min
[INFO] Finished at: 2019-10-10T12:02:36Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project nexus-repository-composer: Compilation failure: Compilation failure: 
[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java:[35,15] 1. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java (at line 35)
[ERROR] 	import static jline.internal.Preconditions.checkNotNull;
[ERROR] 	              ^^^^^
[ERROR] The import jline cannot be resolved
[ERROR] 
[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java:[56,21] 2. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java (at line 56)
[ERROR] 	this.eventManager = checkNotNull(eventManager);
[ERROR] 	                    ^^^^^^^^^^^^
[ERROR] The method checkNotNull(EventManager) is undefined for the type ComposerHostedMetadataFacetImpl
[ERROR] 
[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java:[32,15] 3. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java (at line 32)
[ERROR] 	import static jline.internal.Preconditions.checkNotNull;
[ERROR] 	              ^^^^^
[ERROR] The import jline cannot be resolved
[ERROR] 
[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java:[111,30] 4. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java (at line 111)
[ERROR] 	this.composerJsonExtractor = checkNotNull(composerJsonExtractor);
[ERROR] 	                             ^^^^^^^^^^^^
[ERROR] The method checkNotNull(ComposerJsonExtractor) is undefined for the type ComposerFormatAttributesExtractor
[ERROR] 
[ERROR] Found 4 errors and 0 warnings.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command '/bin/sh -c cd /nexus-repository-composer/; sed -i "s/3.13.0-01/${NEXUS_VERSION}-${NEXUS_BUILD}/g" pom.xml;     mvn clean package;' returned a non-zero code: 1
```

I have attached the Dockerfile to reproduce this issue (Dockerfile-broken.zip) and the last known working version (Dockerfile-last-known-working.zip).
[Dockerfile-broken.zip](https://github.com/sonatype-nexus-community/nexus-repository-composer/files/3712511/Dockerfile.zip)

[Dockerfile-last-known-working.zip](https://github.com/sonatype-nexus-community/nexus-repository-composer/files/3712518/Dockerfile-last-known-working.zip)

**Comment by electrical** [comment]
Please note that its still broken.

When using the latest Nexus version ( 3.20.1 ) I'm getting the following error at startup:

`2019-12-24 11:11:18,382+0000 ERROR [FelixDispatchQueue] *SYSTEM org.sonatype.nexus.plugins.nexus-repository-composer - FrameworkEvent ERROR - org.sonatype.nexus.plugins.nexus-repository-composer
org.osgi.framework.BundleException: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-composer [239](R 239.0): missing requirement [org.sonatype.nexus.plugins.nexus-repository-composer [239](R 239.0)] osgi.wiring.package; (&(osgi.wiring.package=jline.internal)(version>=2.14.0)) Unresolved requirements: [[org.sonatype.nexus.plugins.nexus-repository-composer [239](R 239.0)] osgi.wiring.package; (&(osgi.wiring.package=jline.internal)(version>=2.14.0))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
2019-12-24 11:11:18,382+0000 ERROR [FelixStartLevel] *SYSTEM Felix - Bundle org.sonatype.nexus.plugins.nexus-repository-composer [239] Error starting reference:file:system/org/sonatype/nexus/plugins/nexus-repository-composer/0.0.2/nexus-repository-composer-0.0.2.jar (org.osgi.framework.BundleException: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-composer [239](R 239.0): missing requirement [org.sonatype.nexus.plugins.nexus-repository-composer [239](R 239.0)] osgi.wiring.package; (&(osgi.wiring.package=jline.internal)(version>=2.14.0)) Unresolved requirements: [[org.sonatype.nexus.plugins.nexus-repository-composer [239](R 239.0)] osgi.wiring.package; (&(osgi.wiring.package=jline.internal)(version>=2.14.0))])
org.osgi.framework.BundleException: Unable to resolve org.sonatype.nexus.plugins.nexus-repository-composer [239](R 239.0): missing requirement [org.sonatype.nexus.plugins.nexus-repository-composer [239](R 239.0)] osgi.wiring.package; (&(osgi.wiring.package=jline.internal)(version>=2.14.0)) Unresolved requirements: [[org.sonatype.nexus.plugins.nexus-repository-composer [239](R 239.0)] osgi.wiring.package; (&(osgi.wiring.package=jline.internal)(version>=2.14.0))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by tetram** [comment]
Hi,
I built without issue the docker image for version 3.19.1 with the following Dockerfile:

```
ARG NEXUS_VERSION=3.19.1

FROM maven:3-jdk-8-alpine AS build
ARG NEXUS_VERSION=3.19.1
ARG NEXUS_BUILD=01

COPY . /nexus-repository-composer/
RUN cd /nexus-repository-composer/; sed -i "s/3.19.1-01/${NEXUS_VERSION}-${NEXUS_BUILD}/g" pom.xml; \
    mvn clean package;

FROM sonatype/nexus3:$NEXUS_VERSION
ARG NEXUS_VERSION=3.19.1
ARG NEXUS_BUILD=01
ARG COMPOSER_VERSION=0.0.2
ARG TARGET_DIR=/opt/sonatype/nexus/system/org/sonatype/nexus/plugins/nexus-repository-composer/${COMPOSER_VERSION}/
USER root
RUN mkdir -p ${TARGET_DIR}; \
    sed -i 's@nexus-repository-maven</feature>@nexus-repository-maven</feature>\n        <feature prerequisite="false" dependency="false" version="0.0.2">nexus-repository-composer</feature>@g' /opt/sonatype/nexus/system/org/sonatype/nexus/assemblies/nexus-core-feature/${NEXUS_VERSION}-${NEXUS_BUILD}/nexus-core-feature-${NEXUS_VERSION}-${NEXUS_BUILD}-features.xml; \
    sed -i 's@<feature name="nexus-repository-maven"@<feature name="nexus-repository-composer" description="org.sonatype.nexus.plugins:nexus-repository-composer" version="0.0.2">\n        <details>org.sonatype.nexus.plugins:nexus-repository-composer</details>\n        <bundle>mvn:org.sonatype.nexus.plugins/nexus-repository-composer/0.0.2</bundle>\n    </feature>\n    <feature name="nexus-repository-maven"@g' /opt/sonatype/nexus/system/org/sonatype/nexus/assemblies/nexus-core-feature/${NEXUS_VERSION}-${NEXUS_BUILD}/nexus-core-feature-${NEXUS_VERSION}-${NEXUS_BUILD}-features.xml;
COPY --from=build /nexus-repository-composer/nexus-repository-composer/target/nexus-repository-composer-${COMPOSER_VERSION}.jar ${TARGET_DIR}
USER nexus
```

I did not encounter any issue with `jline`.

I'll try 3.20 and keep you posted.

**Comment by func0der** [comment]
as this seems to be fixed with the PR or there discussed commits, I am closing it.
/close
