### PR TITLE
Fix: dockerfile for 3.19+

### LINKED ISSUE #49: nexus-repository-composer 0.0.2 does not work with Nexus OSS >3.19.0-01
* **What are you trying to do?**
I am trying to use the current 0.0.2 with Nexus OSS >3.19.0-01. 

* **What feature or behavior is this required for?**
Using your plugin with an up-to-date version of Nexus OSS.

* **How could we solve this issue? (Not knowing is okay!)**
I think, that the dependency for `jline` got unpublished somehow. I could not find the place in the diff between 3.18.01-01 and 3.19.0-01 though.

* **Anything else?**
The error message during the docker build is the following:

```
Downloaded from rso-public-grid: https://repository.sonatype.org/content/groups/sonatype-public-grid/org/codehaus/groovy/groovy-eclipse-batch/2.4.3-01/groovy-eclipse-batch-2.4.3-01.jar (15 MB at 7.4 MB/s)
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java:[35,15] 1. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java (at line 35)
	import static jline.internal.Preconditions.checkNotNull;
	              ^^^^^
The import jline cannot be resolved

[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java:[56,21] 2. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java (at line 56)
	this.eventManager = checkNotNull(eventManager);
	                    ^^^^^^^^^^^^
The method checkNotNull(EventManager) is undefined for the type ComposerHostedMetadataFacetImpl

[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java:[32,15] 3. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java (at line 32)
	import static jline.internal.Preconditions.checkNotNull;
	              ^^^^^
The import jline cannot be resolved

[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java:[111,30] 4. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java (at line 111)
	this.composerJsonExtractor = checkNotNull(composerJsonExtractor);
	                             ^^^^^^^^^^^^
The method checkNotNull(ComposerJsonExtractor) is undefined for the type ComposerFormatAttributesExtractor

[ERROR] Found 4 errors and 0 warnings.
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:45 min
[INFO] Finished at: 2019-10-10T12:02:36Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project nexus-repository-composer: Compilation failure: Compilation failure: 
[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java:[35,15] 1. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java (at line 35)
[ERROR] 	import static jline.internal.Preconditions.checkNotNull;
[ERROR] 	              ^^^^^
[ERROR] The import jline cannot be resolved
[ERROR] 
[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java:[56,21] 2. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerHostedMetadataFacetImpl.java (at line 56)
[ERROR] 	this.eventManager = checkNotNull(eventManager);
[ERROR] 	                    ^^^^^^^^^^^^
[ERROR] The method checkNotNull(EventManager) is undefined for the type ComposerHostedMetadataFacetImpl
[ERROR] 
[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java:[32,15] 3. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java (at line 32)
[ERROR] 	import static jline.internal.Preconditions.checkNotNull;
[ERROR] 	              ^^^^^
[ERROR] The import jline cannot be resolved
[ERROR] 
[ERROR] /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java:[111,30] 4. ERROR in /nexus-repository-composer/src/main/java/org/sonatype/nexus/repository/composer/internal/ComposerFormatAttributesExtractor.java (at line 111)
[ERROR] 	this.composerJsonExtractor = checkNotNull(composerJsonExtractor);
[ERROR] 	                             ^^^^^^^^^^^^
[ERROR] The method checkNotNull(ComposerJsonExtractor) is undefined for the type ComposerFormatAttributesExtractor
[ERROR] 
[ERROR] Found 4 errors and 0 warnings.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command '/bin/sh -c cd /nexus-repository-composer/; sed -i "s/3.13.0-01/${NEXUS_VERSION}-${NEXUS_BUILD}/g" pom.xml;     mvn clean package;' returned a non-zero code: 1
```

I have attached the Dockerfile to reproduce this issue (Dockerfile-broken.zip) and the last known working version (Dockerfile-last-known-working.zip).
[Dockerfile-broken.zip](https://github.com/sonatype-nexus-community/nexus-repository-composer/files/3712511/Dockerfile.zip)

[Dockerfile-last-known-working.zip](https://github.com/sonatype-nexus-community/nexus-repository-composer/files/3712518/Dockerfile-last-known-working.zip)

### PR DESCRIPTION
**Pull request by tetram**
The goal of this PR is to fix the dockerfile.

This pull request makes the following changes:
* makes dockerfile compliant with the new project structure
* makes dockerfile sed version 3.19.01-01 in pom

It relates to the following issue #s:
* Fixes #49

### CODE REVIEW

**Comment by Rakdos8** [comment]
Should NEXUS_VERSION values follow the sed one ?

**Comment by tetram** [comment]
It's the default build args, idk which version they should be pointing at... Maybe it would be nice to have them matching the default pom version.

I don't know if there is still anyone on this project giving guidelines^^

**Comment by electrical** [comment]
I've applied the proposed changes to my own build of it and works all fine now even with 3.20.1 build.
Just have to make sure that the jar file is created for the specific nexus version.

**Comment by taz77** [comment]
I made the changes missing here in PR #65

**Comment by bhamail** [comment]
I'm pretty sure this is fixed by commit: 5679dcb, so closing this PR. If I'm mistaken, please holler.
